[package]
name = "mallow-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true

[[bin]]
name = "mallow"
path = "src/main.rs"

[dependencies]
mallow-core = { workspace = true }
mallow-luau-toolchain = { workspace = true, optional = true }

anyhow = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-chrome = { workspace = true, optional = true }
tracing-subscriber = { workspace = true }

[features]
default = []
luau-toolchain = ["dep:mallow-luau-toolchain"]
profile = ["dep:tracing-chrome"]
visualize = ["mallow-core/visualize"]
