[workspace]
members = ["crates/mallow-cli", "crates/mallow-core", "crates/mallow-luau-toolchain"]
resolver = "3"

[workspace.package]
version = "0.5.0"
edition = "2024"
license = "AGPL-3.0-only"
readme = "README.md"

[workspace.dependencies]
mallow-core = { path = "crates/mallow-core" }
mallow-luau-toolchain = { path = "crates/mallow-luau-toolchain" }

anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
directories = "6.0.0"
either = "1.18.0"
fs2 = "0.4.3"
id-arena = "2.3.0"
libtest-mimic = "0.8.2"
reqwest = { version = "0.13.4", features = ["blocking", "rustls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.11.0"
smallvec = "1.15.1"
smol_str = "0.3.5"
tempfile = "3.26.0"
thiserror = "2.0.19"
tracing = "0.1.41"
tracing-chrome = "0.7.2"
tracing-subscriber = "0.3.22"
wait-timeout = "0.2.1"
zip = { version = "8.6.0", features = ["deflate"] }
