//! Download, verify, cache, and run Luau release tools.

use std::ffi::OsStr;
use std::fs::{self, File, OpenOptions};
use std::io::{self, Cursor, Read, Write};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{Duration, Instant};

use directories::ProjectDirs;
use fs2::FileExt;
use reqwest::blocking::Client;
use sha2::{Digest, Sha256};
use thiserror::Error;
use zip::ZipArchive;

macro_rules! os_bin {
    ($name:literal) => {
        if cfg!(windows) {
            concat!($name, ".exe")
        } else {
            $name
        }
    };
}

/// Maximum compressed archive response accepted from a download, in bytes.
const MAX_ARCHIVE_BYTES: usize = 128 * 1024 * 1024;

/// Maximum uncompressed size accepted for one executable, in bytes.
const MAX_EXECUTABLE_BYTES: u64 = 64 * 1024 * 1024;

/// Maximum size accepted for a cached installation manifest, in bytes.
const MAX_MANIFEST_BYTES: u64 = 4 * 1024;

/// Hidden file name used for metadata describing a cached installation.
const INSTALLATION_MANIFEST_NAME: &str = ".manifest";

/// Hidden file name used for the registry-authenticated source archive.
const SOURCE_ARCHIVE_NAME: &str = ".archive";

/// Version marker for the line-oriented installation manifest format.
const INSTALLATION_MANIFEST_VERSION: &str = "mallow-toolchain-manifest-v3";

/// Number of executables known to the toolchain manager.
const TOOL_COUNT: usize = 4;

/// Number of executables required to compile and run Luau.
const REQUIRED_TOOL_COUNT: usize = 3;

/// Maximum time allowed for a single HTTP request, including response transfer.
const REQUEST_TIMEOUT: Duration = Duration::from_secs(60);

/// Maximum number of attempts made for one transient download failure.
const DOWNLOAD_ATTEMPTS: usize = 3;

/// Initial delay between attempts for one transient download failure.
const DOWNLOAD_RETRY_DELAY: Duration = Duration::from_millis(1000);

/// Maximum time an installer waits for another process to release its advisory lock.
const INSTALL_LOCK_TIMEOUT: Duration = Duration::from_secs(120);

/// Registry data generated by the build script from the verified release inventory.
mod registry_generated {
    use super::{BytecodeVersion, PlatformAsset, Release};

    include!(concat!(env!("OUT_DIR"), "/registry_generated.rs"));
}

/// A Luau bytecode format emitted by a compiler release.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum BytecodeVersion {
    /// Bytecode format 4.
    V4 = 4,
    /// Bytecode format 5.
    V5 = 5,
    /// Bytecode format 6.
    V6 = 6,
    /// Bytecode format 7.
    V7 = 7,
    /// Bytecode format 8.
    V8 = 8,
    /// Bytecode format 9.
    V9 = 9,
    /// Bytecode format 10.
    V10 = 10,
    /// Bytecode format 11.
    V11 = 11,
}

/// Error returned when a bytecode number is outside the supported range.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct InvalidBytecodeVersion {
    /// Number that could not be converted to a supported bytecode version.
    pub number: u8,
}

impl std::fmt::Display for InvalidBytecodeVersion {
    /// Formats the unsupported bytecode number.
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            formatter,
            "unsupported Luau bytecode version {}",
            self.number
        )
    }
}

impl std::error::Error for InvalidBytecodeVersion {}

impl TryFrom<u8> for BytecodeVersion {
    type Error = InvalidBytecodeVersion;

    /// Converts a wire-format bytecode number into its typed representation.
    fn try_from(number: u8) -> Result<Self, Self::Error> {
        match number {
            4 => Ok(Self::V4),
            5 => Ok(Self::V5),
            6 => Ok(Self::V6),
            7 => Ok(Self::V7),
            8 => Ok(Self::V8),
            9 => Ok(Self::V9),
            10 => Ok(Self::V10),
            11 => Ok(Self::V11),
            number => Err(InvalidBytecodeVersion { number }),
        }
    }
}

impl From<BytecodeVersion> for u8 {
    /// Returns the numeric bytecode identifier encoded by this value.
    fn from(version: BytecodeVersion) -> Self {
        version as u8
    }
}

impl std::fmt::Display for BytecodeVersion {
    /// Writes the numeric bytecode identifier used in diagnostics.
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        u8::from(*self).fmt(formatter)
    }
}

/// A downloadable Luau archive for one target triple.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct PlatformAsset {
    /// Rust target triple used to select this archive.
    pub target: &'static str,
    /// File name used by the upstream release.
    pub archive_name: &'static str,
    /// HTTPS URL from which the archive is downloaded.
    pub url: &'static str,
    /// Lowercase SHA-256 digest of the complete archive.
    pub sha256: &'static str,
}

/// Metadata for one Luau release, including its bytecode format and platform archives.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Release {
    /// Upstream release number, such as `0.728`.
    pub version: &'static str,
    /// Bytecode format emitted by this compiler.
    pub bytecode: BytecodeVersion,
    /// Platform-specific archives belonging to this release.
    assets: &'static [PlatformAsset],
}

impl Release {
    /// Returns the archive matching the current operating system and CPU architecture.
    fn asset_for_current_platform(&self) -> Option<&'static PlatformAsset> {
        self.assets
            .iter()
            .find(|asset| asset.target == CURRENT_TARGET)
    }
}

/// Target triple used for a 64-bit Windows process.
#[cfg(all(target_os = "windows", target_arch = "x86_64"))]
const CURRENT_TARGET: &str = "x86_64-pc-windows-msvc";

/// Target triple used for an ARM64 Windows process.
#[cfg(all(target_os = "windows", target_arch = "aarch64"))]
const CURRENT_TARGET: &str = "aarch64-pc-windows-msvc";

/// Target triple used for a 64-bit Intel macOS process.
#[cfg(all(target_os = "macos", target_arch = "x86_64"))]
const CURRENT_TARGET: &str = "x86_64-apple-darwin";

/// Target triple used for an ARM64 macOS process.
#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
const CURRENT_TARGET: &str = "aarch64-apple-darwin";

/// Target triple used for a 64-bit glibc Linux process.
#[cfg(all(target_os = "linux", target_env = "gnu", target_arch = "x86_64"))]
const CURRENT_TARGET: &str = "x86_64-unknown-linux-gnu";

/// Target triple used for an ARM64 glibc Linux process.
#[cfg(all(target_os = "linux", target_env = "gnu", target_arch = "aarch64"))]
const CURRENT_TARGET: &str = "aarch64-unknown-linux-gnu";

/// Target triple used for a 64-bit FreeBSD process.
#[cfg(all(target_os = "freebsd", target_arch = "x86_64"))]
const CURRENT_TARGET: &str = "x86_64-unknown-freebsd";

/// Fallback target marker for platforms without a registry asset.
#[cfg(not(any(
    all(target_os = "windows", target_arch = "x86_64"),
    all(target_os = "windows", target_arch = "aarch64"),
    all(target_os = "macos", target_arch = "x86_64"),
    all(target_os = "macos", target_arch = "aarch64"),
    all(target_os = "linux", target_env = "gnu", target_arch = "x86_64"),
    all(target_os = "linux", target_env = "gnu", target_arch = "aarch64"),
    all(target_os = "freebsd", target_arch = "x86_64")
)))]
const CURRENT_TARGET: &str = "unknown";

/// The embedded release registry and lookup operations.
pub struct Registry;

impl Registry {
    /// Returns the complete embedded registry in newest-first order.
    pub fn releases() -> &'static [Release] {
        registry_generated::registry()
    }

    /// Looks up a release by its exact upstream version string.
    pub fn release(version: &str) -> Option<&'static Release> {
        Self::releases()
            .iter()
            .find(|release| release.version == version)
    }

    /// Returns the newest release using a bytecode format.
    pub fn bytecode(bytecode: BytecodeVersion) -> Option<&'static Release> {
        Self::releases()
            .iter()
            .find(|release| release.bytecode == bytecode)
    }

    /// Returns every release using a bytecode format, in registry order.
    pub fn releases_for_bytecode(bytecode: BytecodeVersion) -> Vec<&'static Release> {
        Self::releases()
            .iter()
            .filter(|release| release.bytecode == bytecode)
            .collect()
    }
}

/// Selects a release by exact upstream version or emitted bytecode format.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum VersionSelector<'a> {
    /// Selects the exact upstream release string.
    Release(&'a str),
    /// Selects the newest embedded release producing this bytecode format.
    Bytecode(BytecodeVersion),
}

impl<'a> VersionSelector<'a> {
    /// Creates an exact-release selector.
    pub const fn release(version: &'a str) -> Self {
        Self::Release(version)
    }

    /// Creates a bytecode selector.
    pub const fn bytecode(bytecode: BytecodeVersion) -> Self {
        Self::Bytecode(bytecode)
    }
}

impl<'a> From<&'a str> for VersionSelector<'a> {
    /// Treats a string as an exact release selector.
    fn from(version: &'a str) -> Self {
        Self::Release(version)
    }
}

impl<'a> From<&'a String> for VersionSelector<'a> {
    /// Treats a borrowed string as an exact release selector.
    fn from(version: &'a String) -> Self {
        Self::Release(version)
    }
}

impl From<BytecodeVersion> for VersionSelector<'static> {
    /// Treats a bytecode value as a newest-compatible-release selector.
    fn from(bytecode: BytecodeVersion) -> Self {
        Self::Bytecode(bytecode)
    }
}

/// One executable shipped in a Luau archive.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Tool {
    /// The Luau interpreter.
    Luau,
    /// The Luau static analyzer.
    Analyze,
    /// The Luau compiler.
    Compile,
    /// The Luau AST parser.
    Ast,
}

impl Tool {
    /// Returns the executable's platform-specific file name.
    pub const fn file_name(self) -> &'static str {
        match self {
            Self::Luau => os_bin!("luau"),
            Self::Analyze => os_bin!("luau-analyze"),
            Self::Compile => os_bin!("luau-compile"),
            Self::Ast => os_bin!("luau-ast"),
        }
    }

    /// Returns all tools that may be present in an installation.
    const fn all() -> [Self; TOOL_COUNT] {
        [Self::Luau, Self::Analyze, Self::Compile, Self::Ast]
    }

    /// Returns the tools required to compile and run Luau.
    const fn required() -> [Self; REQUIRED_TOOL_COUNT] {
        [Self::Luau, Self::Analyze, Self::Compile]
    }

    /// Returns this tool's stable position in manifest and digest arrays.
    const fn index(self) -> usize {
        match self {
            Self::Luau => 0,
            Self::Analyze => 1,
            Self::Compile => 2,
            Self::Ast => 3,
        }
    }
}

/// The verified root of one complete Luau release installation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Installation {
    /// Release metadata resolved before installation.
    release: Release,
    /// Directory containing all verified executables.
    root: PathBuf,
}

impl Installation {
    /// Creates an installation value for a verified root directory.
    fn new(release: Release, root: PathBuf) -> Self {
        Self { release, root }
    }

    /// Returns the resolved release metadata.
    pub fn release(&self) -> &Release {
        &self.release
    }

    /// Returns the verified installation root directory.
    pub fn path(&self) -> &Path {
        &self.root
    }

    /// Returns the verified path for one tool.
    pub fn tool_path(&self, tool: Tool) -> PathBuf {
        self.root.join(tool.file_name())
    }

    /// Returns the verified Luau interpreter path.
    pub fn luau_path(&self) -> PathBuf {
        self.tool_path(Tool::Luau)
    }

    /// Returns the verified analyzer path.
    pub fn analyze_path(&self) -> PathBuf {
        self.tool_path(Tool::Analyze)
    }

    /// Returns the verified compiler path.
    pub fn compiler_path(&self) -> PathBuf {
        self.tool_path(Tool::Compile)
    }

    /// Returns the verified path for the AST parser, when available.
    pub fn ast_path(&self) -> Option<PathBuf> {
        let path = self.tool_path(Tool::Ast);
        is_valid_executable(&path).then_some(path)
    }

    /// Builds a process command for one installed tool.
    pub fn command(&self, tool: Tool) -> Command {
        Command::new(self.tool_path(tool))
    }

    /// Builds a process command for the Luau interpreter.
    pub fn luau(&self) -> Command {
        self.command(Tool::Luau)
    }

    /// Builds a process command for the analyzer.
    pub fn analyze(&self) -> Command {
        self.command(Tool::Analyze)
    }

    /// Builds a process command for the compiler.
    pub fn compiler(&self) -> Command {
        self.command(Tool::Compile)
    }

    /// Builds a process command for the AST parser, when available.
    pub fn ast(&self) -> Option<Command> {
        self.ast_path().map(Command::new)
    }
}

/// The default HTTPS downloader backed by reqwest's blocking client.
#[derive(Clone, Debug, Default)]
struct HttpDownloader {
    /// Reusable blocking HTTP client with TLS and redirect support.
    client: Client,
}

impl HttpDownloader {
    /// Fetches an archive and retries transient download failures.
    fn download(&self, url: &str) -> Result<Vec<u8>, DownloadError> {
        for attempt in 0..DOWNLOAD_ATTEMPTS {
            match self.download_once(url) {
                Ok(bytes) => return Ok(bytes),
                Err(error) if error.is_retryable() && attempt + 1 < DOWNLOAD_ATTEMPTS => {
                    std::thread::sleep(DOWNLOAD_RETRY_DELAY * (1_u32 << attempt));
                }
                Err(error) => return Err(error),
            }
        }

        unreachable!("the download attempt count is non-zero")
    }

    /// Makes one request and enforces status, response, and body-size limits.
    fn download_once(&self, url: &str) -> Result<Vec<u8>, DownloadError> {
        let response = self
            .client
            .get(url)
            .timeout(REQUEST_TIMEOUT)
            .send()
            .map_err(|error| DownloadError::Http(error.to_string()))?;
        if !response.status().is_success() {
            return Err(DownloadError::Status(response.status().as_u16()));
        }
        if response
            .content_length()
            .is_some_and(|length| length > MAX_ARCHIVE_BYTES as u64)
        {
            return Err(DownloadError::TooLarge {
                limit: MAX_ARCHIVE_BYTES,
            });
        }
        let mut bytes = Vec::new();
        response
            .take(MAX_ARCHIVE_BYTES as u64 + 1)
            .read_to_end(&mut bytes)
            .map_err(DownloadError::Io)?;
        if bytes.len() > MAX_ARCHIVE_BYTES {
            return Err(DownloadError::TooLarge {
                limit: MAX_ARCHIVE_BYTES,
            });
        }
        Ok(bytes)
    }
}

/// Failures encountered while obtaining a Luau tool archive.
#[derive(Debug, Error)]
pub enum DownloadError {
    /// The HTTP client failed before receiving a successful response.
    #[error("HTTP request failed: {0}")]
    Http(String),
    /// The server returned a non-success status code.
    #[error("HTTP server returned status {0}")]
    Status(u16),
    /// Reading the response body failed.
    #[error("could not read HTTP response: {0}")]
    Io(#[source] io::Error),
    /// The response body exceeded [`MAX_ARCHIVE_BYTES`].
    #[error("HTTP response exceeds the {limit}-byte archive limit")]
    TooLarge {
        /// Maximum accepted response size in bytes.
        limit: usize,
    },
}

impl DownloadError {
    /// Reports whether another request may succeed without changing the input.
    fn is_retryable(&self) -> bool {
        match self {
            Self::Http(_) | Self::Io(_) => true,
            Self::Status(status) => (500..=599).contains(status),
            Self::TooLarge { .. } => false,
        }
    }
}

/// Errors returned by registry lookup, caching, installation, and command creation.
#[derive(Debug, Error)]
pub enum Error {
    /// No embedded release has the requested version.
    #[error("unknown Luau release `{0}`")]
    UnknownRelease(String),
    /// No embedded release produces the requested bytecode format.
    #[error("no Luau release produces bytecode version {0}")]
    UnknownBytecode(BytecodeVersion),
    /// The release exists but has no archive for this target.
    #[error("release `{release}` has no archive for target `{target}`")]
    UnsupportedPlatform {
        /// Requested release number.
        release: String,
        /// Target triple that was requested.
        target: String,
    },
    /// A local or process operation failed with an I/O error.
    #[error("I/O operation failed: {0}")]
    Io(#[from] io::Error),
    /// Downloading the archive failed.
    #[error(transparent)]
    Download(#[from] DownloadError),
    /// The downloaded bytes do not match the registry digest.
    #[error("SHA-256 mismatch for `{release}`: expected {expected}, got {actual}")]
    ChecksumMismatch {
        /// Release whose archive was checked.
        release: String,
        /// Digest recorded in the registry.
        expected: String,
        /// Digest calculated from downloaded bytes.
        actual: String,
    },
    /// The archive did not contain exactly one usable copy of each required tool.
    #[error("invalid Luau archive: {0}")]
    InvalidArchive(String),
    /// An archive or extracted executable exceeded a configured resource limit.
    #[error("{resource} is {size} bytes, exceeding the {limit}-byte limit")]
    TooLarge {
        /// Resource whose size was bounded.
        resource: &'static str,
        /// Observed size in bytes.
        size: u64,
        /// Maximum permitted size in bytes.
        limit: u64,
    },
    /// Another process held an installation lock for too long.
    #[error("timed out waiting for installation lock `{0}`")]
    InstallLockTimeout(PathBuf),
    /// The cache's `installations` path is a symlink or another non-directory entry.
    #[error("cache installations path `{0}` is not a directory")]
    InvalidInstallationsDirectory(PathBuf),
    /// A release name or path component would escape the cache directory.
    #[error("invalid release name `{0}`")]
    InvalidReleaseName(String),
}

/// A persistent cache rooted at the conventional per-user cache directory.
#[derive(Clone, Debug)]
struct Cache {
    /// Directory containing all hash-keyed release installations.
    root: PathBuf,
}

impl Cache {
    /// Creates a cache using the platform's conventional cache directory.
    fn new() -> Result<Self, Error> {
        if let Some(path) = std::env::var_os("MALLOW_TOOLCHAIN_CACHE_DIR") {
            return Ok(Self::at(path));
        }
        let project = ProjectDirs::from("", "mallow", "luau-toolchain")
            .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "no user cache directory"))?;
        Ok(Self::at(project.cache_dir()))
    }

    /// Creates a cache rooted at an explicit directory.
    fn at(path: impl Into<PathBuf>) -> Self {
        let path = path.into();
        let root = std::path::absolute(&path).unwrap_or(path);
        Self { root }
    }

    /// Returns this cache's root without creating it.
    fn root(&self) -> &Path {
        &self.root
    }

    /// Returns the hash-keyed root directory for a release archive.
    fn installation_path_for_hash(&self, release: &str, sha256: &str) -> Result<PathBuf, Error> {
        validate_release_name(release)?;
        validate_hash(sha256)?;

        let path = self
            .root
            .join("installations")
            .join(format!("{release}-{}", sha256.to_ascii_lowercase()));
        Ok(path)
    }

    /// Downloads, verifies, and publishes a release archive unless already cached.
    fn ensure(
        &self,
        release: &Release,
        downloader: &HttpDownloader,
    ) -> Result<Installation, Error> {
        let asset =
            release
                .asset_for_current_platform()
                .ok_or_else(|| Error::UnsupportedPlatform {
                    release: release.version.to_owned(),
                    target: CURRENT_TARGET.to_owned(),
                })?;
        let destination = self.installation_path_for_hash(release.version, asset.sha256)?;
        self.ensure_installations_dir()?;

        let lock = lock_path(&destination);
        let _guard = InstallationLock::acquire(lock)?;
        if is_valid_installation(&destination, asset.sha256) {
            return Ok(Installation::new(*release, destination));
        }

        let archive = downloader.download(asset.url)?;
        self.install_archive_unlocked(release, &archive, asset.sha256, destination)
    }

    /// Verifies and publishes an archive extraction into the cache.
    #[cfg(test)]
    fn install_archive(
        &self,
        release: &Release,
        archive: &[u8],
        expected_sha256: &str,
    ) -> Result<Installation, Error> {
        validate_release_name(release.version)?;
        ensure_archive_size(archive.len())?;
        validate_hash(expected_sha256)?;

        let actual = digest(archive);
        if !expected_sha256.eq_ignore_ascii_case(&actual) {
            return Err(Error::ChecksumMismatch {
                release: release.version.to_owned(),
                expected: expected_sha256.to_owned(),
                actual,
            });
        }

        let destination = self.installation_path_for_hash(release.version, expected_sha256)?;
        self.ensure_installations_dir()?;

        let _guard = InstallationLock::acquire(lock_path(&destination))?;
        if is_valid_installation(&destination, expected_sha256) {
            return Ok(Installation::new(*release, destination));
        }

        self.install_archive_unlocked(release, archive, expected_sha256, destination)
    }

    /// Creates the cache's installation parent only when it is absent and real.
    fn ensure_installations_dir(&self) -> Result<(), Error> {
        let installations = self.root.join("installations");
        match fs::symlink_metadata(&installations) {
            Ok(metadata) if metadata.file_type().is_dir() => Ok(()),
            Ok(_) => Err(Error::InvalidInstallationsDirectory(installations)),
            Err(error) if error.kind() == io::ErrorKind::NotFound => {
                fs::create_dir_all(&installations)?;
                let metadata = fs::symlink_metadata(&installations)?;
                if metadata.file_type().is_dir() {
                    Ok(())
                } else {
                    Err(Error::InvalidInstallationsDirectory(installations))
                }
            }
            Err(error) => Err(Error::Io(error)),
        }
    }

    /// Extracts and publishes an archive while the destination lock is held.
    fn install_archive_unlocked(
        &self,
        release: &Release,
        archive: &[u8],
        expected_sha256: &str,
        destination: PathBuf,
    ) -> Result<Installation, Error> {
        ensure_archive_size(archive.len())?;
        validate_hash(expected_sha256)?;

        let actual = digest(archive);
        if !expected_sha256.eq_ignore_ascii_case(&actual) {
            return Err(Error::ChecksumMismatch {
                release: release.version.to_owned(),
                expected: expected_sha256.to_owned(),
                actual,
            });
        }

        let parent = destination
            .parent()
            .ok_or_else(|| Error::InvalidArchive("cache path has no parent".to_owned()))?;
        let temporary = tempfile::tempdir_in(parent)?;
        let tool_sha256 = process_archive_tools(archive, Some(temporary.path()))?;

        let manifest = InstallationManifest::new(expected_sha256, tool_sha256);
        write_installation_manifest(temporary.path(), &manifest)?;
        write_source_archive(temporary.path(), archive)?;
        remove_stale_destination(&destination)?;
        fs::rename(temporary.path(), &destination)?;

        Ok(Installation::new(*release, destination))
    }
}

/// An advisory lock guarding one hash-keyed cache destination.
struct InstallationLock {
    /// Open handle retaining the advisory lock while installation runs.
    file: File,
}

impl InstallationLock {
    /// Opens a persistent lock file and waits for its exclusive advisory lock.
    fn acquire(path: PathBuf) -> Result<Self, Error> {
        let started = Instant::now();
        let file = OpenOptions::new()
            .read(true)
            .write(true)
            .create(true)
            .truncate(false)
            .open(&path)?;
        loop {
            match file.try_lock_exclusive() {
                Ok(()) => return Ok(Self { file }),
                Err(error) if error.kind() == io::ErrorKind::WouldBlock => {
                    if started.elapsed() >= INSTALL_LOCK_TIMEOUT {
                        return Err(Error::InstallLockTimeout(path));
                    }
                    std::thread::sleep(Duration::from_millis(25));
                }
                Err(error) => return Err(Error::Io(error)),
            }
        }
    }
}

impl Drop for InstallationLock {
    /// Releases the advisory lock while leaving its inode for future installers.
    fn drop(&mut self) {
        let _ = FileExt::unlock(&self.file);
    }
}

/// A configured Luau release manager with a persistent cache and HTTPS downloader.
#[derive(Clone, Debug)]
pub struct Manager {
    /// Cache in which release installations are published.
    cache: Cache,
    /// Concrete downloader used for registry archives.
    downloader: HttpDownloader,
}

impl Manager {
    /// Creates a manager using the conventional cache and HTTPS downloader.
    pub fn new() -> Result<Self, Error> {
        Ok(Self {
            cache: Cache::new()?,
            downloader: HttpDownloader::default(),
        })
    }

    /// Creates a manager rooted at an explicit cache directory.
    pub fn at(path: impl Into<PathBuf>) -> Self {
        Self {
            cache: Cache::at(path),
            downloader: HttpDownloader::default(),
        }
    }

    /// Returns the cache root used by this manager.
    pub fn cache_root(&self) -> &Path {
        self.cache.root()
    }

    /// Resolves an exact release or bytecode selector to release metadata.
    pub fn resolve<'a, S>(&self, selector: S) -> Result<&'static Release, Error>
    where
        S: Into<VersionSelector<'a>>,
    {
        match selector.into() {
            VersionSelector::Release(version) => {
                Registry::release(version).ok_or_else(|| Error::UnknownRelease(version.to_owned()))
            }
            VersionSelector::Bytecode(bytecode) => {
                let newest = Registry::bytecode(bytecode);
                let current = Registry::releases().iter().find(|release| {
                    release.bytecode == bytecode && release.asset_for_current_platform().is_some()
                });
                current.or(newest).ok_or(Error::UnknownBytecode(bytecode))
            }
        }
    }

    /// Installs the release selected by an exact version or bytecode format.
    pub fn install<'a, S>(&self, selector: S) -> Result<Installation, Error>
    where
        S: Into<VersionSelector<'a>>,
    {
        let release = self.resolve(selector)?;
        self.cache.ensure(release, &self.downloader)
    }

    /// Installs an exact release and returns its complete installation.
    pub fn install_release(&self, version: &str) -> Result<Installation, Error> {
        self.install(VersionSelector::Release(version))
    }

    /// Installs the newest release emitting a bytecode format.
    pub fn install_bytecode(&self, bytecode: BytecodeVersion) -> Result<Installation, Error> {
        self.install(VersionSelector::Bytecode(bytecode))
    }

    /// Builds a command for the selected release and tool after verifying its installation.
    pub fn command<'a, S>(&self, selector: S, tool: Tool) -> Result<Command, Error>
    where
        S: Into<VersionSelector<'a>>,
    {
        Ok(self.install(selector)?.command(tool))
    }

    /// Builds a command for an exact release and tool.
    pub fn command_release(&self, version: &str, tool: Tool) -> Result<Command, Error> {
        self.command(VersionSelector::Release(version), tool)
    }

    /// Builds a command for the newest release emitting a bytecode format.
    pub fn command_bytecode(
        &self,
        bytecode: BytecodeVersion,
        tool: Tool,
    ) -> Result<Command, Error> {
        self.command(VersionSelector::Bytecode(bytecode), tool)
    }

    /// Builds a command for the selected release's Luau interpreter.
    pub fn luau<'a, S>(&self, selector: S) -> Result<Command, Error>
    where
        S: Into<VersionSelector<'a>>,
    {
        self.command(selector, Tool::Luau)
    }

    /// Builds a command for the selected release's analyzer.
    pub fn analyze<'a, S>(&self, selector: S) -> Result<Command, Error>
    where
        S: Into<VersionSelector<'a>>,
    {
        self.command(selector, Tool::Analyze)
    }

    /// Builds a command for the selected release's compiler.
    pub fn compiler<'a, S>(&self, selector: S) -> Result<Command, Error>
    where
        S: Into<VersionSelector<'a>>,
    {
        self.command(selector, Tool::Compile)
    }

    /// Builds a command for the selected release's AST parser, when available.
    pub fn ast<'a, S>(&self, selector: S) -> Result<Option<Command>, Error>
    where
        S: Into<VersionSelector<'a>>,
    {
        Ok(self.install(selector)?.ast())
    }
}

/// Returns the stable lock path associated with one installation destination.
fn lock_path(destination: &Path) -> PathBuf {
    let mut path = destination.as_os_str().to_owned();
    path.push(".install.lock");
    PathBuf::from(path)
}

/// Computes the lowercase SHA-256 digest used in cache identity paths.
fn digest(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    finish_digest(hasher)
}

/// Converts a finalized SHA-256 hasher into lowercase hexadecimal text.
fn finish_digest(hasher: Sha256) -> String {
    use std::fmt::Write as _;

    let bytes = hasher.finalize();
    let bytes: &[u8] = bytes.as_ref();
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(&mut output, "{byte:02x}").expect("writing to a String is infallible");
    }
    output
}

/// Metadata recorded after an archive has been extracted successfully.
///
/// The fixed tool order matches [`Tool::all`], so parsing does not need a
/// runtime serialization dependency or any caller-provided file names.
struct InstallationManifest {
    /// Lowercase SHA-256 digest of the verified source archive.
    archive_sha256: String,
    /// Lowercase SHA-256 digests in [`Tool::all`] order.
    ///
    /// A missing digest means the release does not ship that optional tool.
    tool_sha256: [Option<String>; TOOL_COUNT],
}

impl InstallationManifest {
    /// Creates manifest metadata from the archive identity and extracted tool digests.
    fn new(expected_archive_sha256: &str, tool_sha256: [Option<String>; TOOL_COUNT]) -> Self {
        Self {
            archive_sha256: expected_archive_sha256.to_ascii_lowercase(),
            tool_sha256,
        }
    }

    /// Serializes the bounded, line-oriented manifest format.
    fn as_bytes(&self) -> Vec<u8> {
        format!(
            "{INSTALLATION_MANIFEST_VERSION}\narchive_sha256={}\nluau_sha256={}\nluau_analyze_sha256={}\nluau_compile_sha256={}\nluau_ast_sha256={}\n",
            self.archive_sha256,
            self.tool_sha256[0].as_deref().unwrap_or("missing"),
            self.tool_sha256[1].as_deref().unwrap_or("missing"),
            self.tool_sha256[2].as_deref().unwrap_or("missing"),
            self.tool_sha256[3].as_deref().unwrap_or("missing"),
        )
        .into_bytes()
    }
}

/// Computes a bounded SHA-256 digest for one extracted executable.
fn digest_file(path: &Path) -> Result<String, Error> {
    let mut file = File::open(path)?;
    let mut hasher = Sha256::new();
    let mut buffer = [0_u8; 8192];
    let mut total = 0_u64;
    loop {
        let read = file.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        total = total.saturating_add(read as u64);
        if total > MAX_EXECUTABLE_BYTES {
            return Err(Error::TooLarge {
                resource: "executable file",
                size: total,
                limit: MAX_EXECUTABLE_BYTES,
            });
        }
        hasher.update(&buffer[..read]);
    }
    Ok(finish_digest(hasher))
}

/// Writes a manifest into a temporary extraction directory before publication.
fn write_installation_manifest(
    installation: &Path,
    manifest: &InstallationManifest,
) -> Result<(), Error> {
    let bytes = manifest.as_bytes();
    if bytes.len() as u64 > MAX_MANIFEST_BYTES {
        return Err(Error::TooLarge {
            resource: "installation manifest",
            size: bytes.len() as u64,
            limit: MAX_MANIFEST_BYTES,
        });
    }

    let path = installation.join(INSTALLATION_MANIFEST_NAME);
    let mut file = OpenOptions::new().write(true).create_new(true).open(path)?;
    file.write_all(&bytes)?;
    file.sync_all()?;

    Ok(())
}

/// Retains the registry-authenticated archive beside its extracted tools.
fn write_source_archive(installation: &Path, archive: &[u8]) -> Result<(), Error> {
    ensure_archive_size(archive.len())?;

    let path = installation.join(SOURCE_ARCHIVE_NAME);
    let mut file = OpenOptions::new().write(true).create_new(true).open(path)?;
    file.write_all(archive)?;
    file.sync_all()?;

    Ok(())
}

/// Reads a bounded source archive and authenticates it with registry metadata.
fn read_verified_source_archive(
    installation: &Path,
    expected_archive_sha256: &str,
) -> Option<Vec<u8>> {
    let path = installation.join(SOURCE_ARCHIVE_NAME);
    let metadata = fs::symlink_metadata(&path).ok()?;
    if !metadata.file_type().is_file()
        || metadata.len() == 0
        || metadata.len() > MAX_ARCHIVE_BYTES as u64
    {
        return None;
    }

    let file = File::open(path).ok()?;
    let mut archive = Vec::with_capacity(metadata.len() as usize);
    file.take(MAX_ARCHIVE_BYTES as u64 + 1)
        .read_to_end(&mut archive)
        .ok()?;

    if archive.len() > MAX_ARCHIVE_BYTES
        || !digest(&archive).eq_ignore_ascii_case(expected_archive_sha256)
    {
        return None;
    }

    Some(archive)
}

/// Validates, hashes, and optionally extracts every archive tool.
fn process_archive_tools(
    archive: &[u8],
    destination: Option<&Path>,
) -> Result<[Option<String>; TOOL_COUNT], Error> {
    ensure_archive_size(archive.len())?;

    let mut archive_reader = ZipArchive::new(Cursor::new(archive))
        .map_err(|error| Error::InvalidArchive(error.to_string()))?;
    let mut digests: [Option<String>; TOOL_COUNT] = std::array::from_fn(|_| None);
    for index in 0..archive_reader.len() {
        let mut entry = archive_reader
            .by_index(index)
            .map_err(|error| Error::InvalidArchive(error.to_string()))?;
        if entry
            .unix_mode()
            .is_some_and(|mode| mode & 0o170000 == 0o120000)
        {
            return Err(Error::InvalidArchive(
                "symbolic links are not allowed".to_owned(),
            ));
        }
        if entry.is_dir() {
            continue;
        }

        let enclosed = entry
            .enclosed_name()
            .ok_or_else(|| Error::InvalidArchive("path traversal entry".to_owned()))?;
        let Some(tool) = tool_for_archive_name(enclosed.file_name()) else {
            continue;
        };

        let tool_index = tool.index();
        if digests[tool_index].is_some() {
            return Err(Error::InvalidArchive(format!(
                "archive contains duplicate {} executable",
                tool.file_name()
            )));
        }

        if entry.size() > MAX_EXECUTABLE_BYTES {
            return Err(Error::TooLarge {
                resource: "executable entry",
                size: entry.size(),
                limit: MAX_EXECUTABLE_BYTES,
            });
        }

        let output_path = destination.map(|path| path.join(tool.file_name()));
        let mut output = output_path.as_ref().map(File::create).transpose()?;
        let mut hasher = Sha256::new();
        let mut buffer = [0_u8; 8192];
        let mut total = 0_u64;

        loop {
            let read = entry.read(&mut buffer)?;
            if read == 0 {
                break;
            }
            total = total.saturating_add(read as u64);
            if total > MAX_EXECUTABLE_BYTES {
                return Err(Error::TooLarge {
                    resource: "executable entry",
                    size: total,
                    limit: MAX_EXECUTABLE_BYTES,
                });
            }
            hasher.update(&buffer[..read]);
            if let Some(output) = &mut output {
                output.write_all(&buffer[..read])?;
            }
        }

        if total == 0 {
            return Err(Error::InvalidArchive(format!(
                "{} executable is empty",
                tool.file_name()
            )));
        }

        if let (Some(output), Some(output_path)) = (output, output_path) {
            output.sync_all()?;
            set_executable_permissions(&output_path)?;
        }
        digests[tool_index] = Some(finish_digest(hasher));
    }

    if let Some(missing) = Tool::required()
        .into_iter()
        .find(|tool| digests[tool.index()].is_none())
    {
        return Err(Error::InvalidArchive(format!(
            "archive does not contain {}",
            missing.file_name()
        )));
    }

    Ok(digests)
}

/// Reads and validates a bounded manifest from an existing installation.
fn read_installation_manifest(installation: &Path) -> Option<InstallationManifest> {
    let path = installation.join(INSTALLATION_MANIFEST_NAME);
    let metadata = fs::symlink_metadata(&path).ok()?;
    if !metadata.file_type().is_file() || metadata.len() == 0 || metadata.len() > MAX_MANIFEST_BYTES
    {
        return None;
    }

    let file = File::open(path).ok()?;
    let mut bytes = Vec::new();
    file.take(MAX_MANIFEST_BYTES.saturating_add(1))
        .read_to_end(&mut bytes)
        .ok()?;

    if bytes.len() as u64 > MAX_MANIFEST_BYTES {
        return None;
    }

    parse_installation_manifest(&bytes)
}

/// Parses the exact line-oriented manifest format without accepting unknown fields.
fn parse_installation_manifest(bytes: &[u8]) -> Option<InstallationManifest> {
    let text = std::str::from_utf8(bytes).ok()?;
    if !text.ends_with('\n') {
        return None;
    }

    let mut lines = text.split_terminator('\n');
    if lines.next()? != INSTALLATION_MANIFEST_VERSION {
        return None;
    }

    let archive_sha256 = parse_manifest_digest(lines.next()?, "archive_sha256=")?;
    let luau_sha256 = Some(parse_manifest_digest(lines.next()?, "luau_sha256=")?);
    let analyze_sha256 = Some(parse_manifest_digest(
        lines.next()?,
        "luau_analyze_sha256=",
    )?);
    let compile_sha256 = Some(parse_manifest_digest(
        lines.next()?,
        "luau_compile_sha256=",
    )?);
    let ast_sha256 = parse_optional_manifest_digest(lines.next()?, "luau_ast_sha256=")?;

    if lines.next().is_some() {
        return None;
    }

    Some(InstallationManifest {
        archive_sha256,
        tool_sha256: [luau_sha256, analyze_sha256, compile_sha256, ast_sha256],
    })
}

/// Parses and canonicalizes one manifest SHA-256 field.
fn parse_manifest_digest(line: &str, prefix: &str) -> Option<String> {
    let value = line.strip_prefix(prefix)?;
    validate_hash(value).ok()?;
    Some(value.to_ascii_lowercase())
}

/// Parses one optional manifest SHA-256 field.
fn parse_optional_manifest_digest(line: &str, prefix: &str) -> Option<Option<String>> {
    let value = line.strip_prefix(prefix)?;
    if value == "missing" {
        return Some(None);
    }

    Some(Some(parse_manifest_digest(line, prefix)?))
}

/// Rejects release strings that could escape the cache directory.
fn validate_release_name(release: &str) -> Result<(), Error> {
    if release.is_empty()
        || release == "."
        || release == ".."
        || release.chars().any(|character| {
            !(character.is_ascii_alphanumeric() || matches!(character, '.' | '-' | '_'))
        })
    {
        return Err(Error::InvalidReleaseName(release.to_owned()));
    }
    Ok(())
}

/// Validates a lowercase or uppercase hexadecimal SHA-256 digest.
fn validate_hash(hash: &str) -> Result<(), Error> {
    if hash.len() != 64 || !hash.chars().all(|character| character.is_ascii_hexdigit()) {
        return Err(Error::InvalidArchive(
            "registry SHA-256 must contain 64 hexadecimal digits".to_owned(),
        ));
    }

    if hash.bytes().all(|character| character == b'0') {
        return Err(Error::InvalidArchive(
            "registry SHA-256 must not be all zeroes".to_owned(),
        ));
    }

    Ok(())
}

/// Rejects an archive whose compressed response exceeds the download limit.
fn ensure_archive_size(size: usize) -> Result<(), Error> {
    if size > MAX_ARCHIVE_BYTES {
        return Err(Error::TooLarge {
            resource: "archive",
            size: size as u64,
            limit: MAX_ARCHIVE_BYTES as u64,
        });
    }

    Ok(())
}

/// Maps an archive basename to one of the four supported tools.
fn tool_for_archive_name(name: Option<&OsStr>) -> Option<Tool> {
    let name = name.and_then(OsStr::to_str)?;

    Tool::all()
        .into_iter()
        .find(|tool| tool.file_name() == name)
}

/// Reports whether a cache path matches its expected archive and tool digests.
fn is_valid_installation(path: &Path, expected_archive_sha256: &str) -> bool {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(_) => return false,
    };

    if !metadata.file_type().is_dir() {
        return false;
    }

    let Some(manifest) = read_installation_manifest(path) else {
        return false;
    };

    if !manifest
        .archive_sha256
        .eq_ignore_ascii_case(expected_archive_sha256)
    {
        return false;
    }

    let Some(archive) = read_verified_source_archive(path, expected_archive_sha256) else {
        return false;
    };

    let Ok(trusted_tool_sha256) = process_archive_tools(&archive, None) else {
        return false;
    };

    if manifest.tool_sha256 != trusted_tool_sha256 {
        return false;
    }

    Tool::all().into_iter().all(|tool| {
        let tool_path = path.join(tool.file_name());
        match trusted_tool_sha256[tool.index()].as_ref() {
            Some(expected) => {
                is_valid_executable(&tool_path)
                    && digest_file(&tool_path).is_ok_and(|actual| actual == *expected)
            }
            None => !tool_path.exists(),
        }
    })
}

/// Reports whether a path is a regular, non-symlink, non-empty executable file.
fn is_valid_executable(path: &Path) -> bool {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(_) => return false,
    };

    if !metadata.file_type().is_file() || metadata.len() == 0 {
        return false;
    }

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        metadata.permissions().mode() & 0o111 != 0
    }
    #[cfg(not(unix))]
    {
        true
    }
}

/// Removes a stale destination without following symlinks or recursively deleting a file.
fn remove_stale_destination(path: &Path) -> Result<(), Error> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_dir() => fs::remove_dir_all(path)?,
        Ok(_) => fs::remove_file(path)?,
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => return Err(Error::Io(error)),
    }

    Ok(())
}

/// Marks an extracted executable as owner/group/world executable on Unix.
#[cfg(unix)]
fn set_executable_permissions(path: &Path) -> Result<(), Error> {
    use std::os::unix::fs::PermissionsExt;

    let mut permissions = fs::metadata(path)?.permissions();
    permissions.set_mode(0o755);
    fs::set_permissions(path, permissions)?;

    Ok(())
}

/// Leaves executable permissions to the platform's file-type semantics.
#[cfg(not(unix))]
fn set_executable_permissions(_path: &Path) -> Result<(), Error> {
    Ok(())
}

/// Network-free tests for bytecode conversion and complete archive installation.
#[cfg(test)]
mod tests {
    use std::io::Write;

    use zip::write::SimpleFileOptions;

    use super::*;

    /// Creates a ZIP archive containing selected tool entries.
    fn archive<Name>(entries: &[(Name, &[u8])]) -> Vec<u8>
    where
        Name: AsRef<str>,
    {
        let mut output = Cursor::new(Vec::new());
        let mut writer = zip::ZipWriter::new(&mut output);
        for (name, bytes) in entries {
            writer
                .start_file(name.as_ref(), SimpleFileOptions::default())
                .unwrap();
            writer.write_all(bytes).unwrap();
        }
        writer.finish().unwrap();
        output.into_inner()
    }

    /// Provides metadata suitable for network-free extraction tests.
    fn fixture_release() -> Release {
        Release {
            version: "fixture",
            bytecode: BytecodeVersion::V9,
            assets: &[],
        }
    }

    /// Creates a ZIP archive containing every required tool.
    fn complete_archive() -> Vec<u8> {
        archive(&[
            (format!("bin/{}", os_bin!("luau")), b"luau".as_slice()),
            (
                format!("bin/{}", os_bin!("luau-analyze")),
                b"analyze".as_slice(),
            ),
            (
                format!("bin/{}", os_bin!("luau-compile")),
                b"compile".as_slice(),
            ),
            (format!("bin/{}", os_bin!("luau-ast")), b"ast".as_slice()),
        ])
    }

    /// Converts every supported bytecode number and rejects unsupported numbers.
    #[test]
    fn bytecode_conversion_is_typed() {
        assert_eq!(BytecodeVersion::try_from(9), Ok(BytecodeVersion::V9));
        assert_eq!(u8::from(BytecodeVersion::V11), 11);
        assert_eq!(
            BytecodeVersion::try_from(12),
            Err(InvalidBytecodeVersion { number: 12 })
        );
    }

    /// Publishes all tools and exposes their commands.
    #[test]
    fn archive_install_publishes_complete_installation() {
        let directory = tempfile::tempdir().unwrap();
        let cache = Cache::at(directory.path());
        let bytes = archive(&[
            (format!("bin/{}", os_bin!("luau")), b"luau".as_slice()),
            (
                format!("bin/{}", os_bin!("luau-analyze")),
                b"analyze".as_slice(),
            ),
            (
                format!("bin/{}", os_bin!("luau-compile")),
                b"compile".as_slice(),
            ),
            (format!("bin/{}", os_bin!("luau-ast")), b"ast".as_slice()),
        ]);
        let hash = digest(&bytes);
        let installation = cache
            .install_archive(&fixture_release(), &bytes, &hash)
            .unwrap();
        assert_eq!(fs::read(installation.luau_path()).unwrap(), b"luau");
        assert_eq!(fs::read(installation.analyze_path()).unwrap(), b"analyze");
        assert_eq!(fs::read(installation.compiler_path()).unwrap(), b"compile");
        assert_eq!(fs::read(installation.ast_path().unwrap()).unwrap(), b"ast");
        assert_eq!(
            fs::read(installation.path().join(SOURCE_ARCHIVE_NAME)).unwrap(),
            bytes
        );
        assert_eq!(
            installation.command(Tool::Compile).get_program(),
            installation.compiler_path()
        );
        assert_eq!(
            installation.ast().unwrap().get_program(),
            installation.ast_path().unwrap()
        );
    }

    /// Installs historical releases that do not ship the optional AST parser.
    #[test]
    fn archive_without_ast_installs_runtime_tools() {
        let directory = tempfile::tempdir().unwrap();
        let cache = Cache::at(directory.path());
        let bytes = archive(&[
            (format!("bin/{}", os_bin!("luau")), b"luau".as_slice()),
            (
                format!("bin/{}", os_bin!("luau-analyze")),
                b"analyze".as_slice(),
            ),
            (
                format!("bin/{}", os_bin!("luau-compile")),
                b"compile".as_slice(),
            ),
        ]);
        let hash = digest(&bytes);
        let installation = cache
            .install_archive(&fixture_release(), &bytes, &hash)
            .unwrap();

        assert_eq!(fs::read(installation.luau_path()).unwrap(), b"luau");
        assert_eq!(fs::read(installation.compiler_path()).unwrap(), b"compile");
        assert!(installation.ast_path().is_none());
        assert!(installation.ast().is_none());
        assert!(is_valid_installation(installation.path(), &hash));
    }

    /// Resolves a relative cache root before commands can change their working directory.
    #[test]
    fn relative_cache_root_produces_absolute_commands() {
        let current = std::env::current_dir().unwrap();
        let directory = tempfile::tempdir_in(&current).unwrap();
        let relative = directory.path().strip_prefix(&current).unwrap();
        let cache = Cache::at(relative);
        let bytes = complete_archive();
        let hash = digest(&bytes);
        let installation = cache
            .install_archive(&fixture_release(), &bytes, &hash)
            .unwrap();
        let mut command = installation.command(Tool::Luau);
        let child_directory = tempfile::tempdir().unwrap();
        command.current_dir(child_directory.path());

        assert!(cache.root().is_absolute());
        assert!(Path::new(command.get_program()).is_absolute());
    }

    /// Rejects traversal, duplicate, and incomplete archives before publication.
    #[test]
    fn archive_validation_rejects_unsafe_or_incomplete_inputs() {
        let directory = tempfile::tempdir().unwrap();
        let cache = Cache::at(directory.path());
        let traversal = archive(&[(format!("../{}", os_bin!("luau")), b"bad".as_slice())]);
        let hash = digest(&traversal);
        assert!(matches!(
            cache.install_archive(&fixture_release(), &traversal, &hash),
            Err(Error::InvalidArchive(_))
        ));
        let duplicate = archive(&[
            (format!("a/{}", os_bin!("luau")), b"a".as_slice()),
            (format!("b/{}", os_bin!("luau")), b"b".as_slice()),
            (os_bin!("luau-analyze").to_owned(), b"a".as_slice()),
            (os_bin!("luau-compile").to_owned(), b"c".as_slice()),
            (os_bin!("luau-ast").to_owned(), b"ast".as_slice()),
        ]);
        let hash = digest(&duplicate);
        assert!(matches!(
            cache.install_archive(&fixture_release(), &duplicate, &hash),
            Err(Error::InvalidArchive(_))
        ));
    }

    /// Rejects an archive missing one required tool without publishing a partial root.
    #[test]
    fn incomplete_archive_does_not_publish_destination() {
        let directory = tempfile::tempdir().unwrap();
        let cache = Cache::at(directory.path());
        let bytes = archive(&[
            (format!("bin/{}", os_bin!("luau")), b"luau".as_slice()),
            (
                format!("bin/{}", os_bin!("luau-analyze")),
                b"analyze".as_slice(),
            ),
        ]);
        let hash = digest(&bytes);
        let destination = cache.installation_path_for_hash("fixture", &hash).unwrap();

        assert!(matches!(
            cache.install_archive(&fixture_release(), &bytes, &hash),
            Err(Error::InvalidArchive(_))
        ));
        assert!(!destination.exists());
    }

    /// Rejects a checksum mismatch before creating any cache destination.
    #[test]
    fn checksum_mismatch_leaves_no_published_installation() {
        let directory = tempfile::tempdir().unwrap();
        let cache = Cache::at(directory.path());
        let bytes = complete_archive();
        let expected = "f".repeat(64);
        let destination = cache
            .installation_path_for_hash("fixture", &expected)
            .unwrap();

        assert!(matches!(
            cache.install_archive(&fixture_release(), &bytes, &expected),
            Err(Error::ChecksumMismatch { .. })
        ));
        assert!(!destination.exists());
    }

    /// Rejects malformed and all-zero archive identity hashes before extraction.
    #[test]
    fn archive_hash_validation_rejects_malformed_and_zero_values() {
        let cache = Cache::at("target");
        let release = fixture_release();
        let archive = archive(&[(os_bin!("luau").to_owned(), b"luau".as_slice())]);

        assert!(matches!(
            cache.install_archive(&release, &archive, "not-a-sha256"),
            Err(Error::InvalidArchive(_))
        ));
        assert!(matches!(
            cache.install_archive(&release, &archive, &"0".repeat(64)),
            Err(Error::InvalidArchive(_))
        ));
    }

    /// Rejects a pre-existing file where the cache expects its installations directory.
    #[test]
    fn non_directory_installations_parent_is_rejected() {
        let directory = tempfile::tempdir().unwrap();
        let installations = directory.path().join("installations");
        fs::write(&installations, b"not a directory").unwrap();
        let cache = Cache::at(directory.path());
        let bytes = complete_archive();
        let hash = digest(&bytes);

        match cache.install_archive(&fixture_release(), &bytes, &hash) {
            Err(Error::InvalidInstallationsDirectory(actual)) => assert_eq!(actual, installations),
            other => panic!("expected invalid installations directory, got {other:?}"),
        }
    }

    /// Rejects a pre-existing installations symlink instead of writing through it.
    #[cfg(unix)]
    #[test]
    fn installations_symlink_is_rejected() {
        use std::os::unix::fs::symlink;

        let directory = tempfile::tempdir().unwrap();
        let outside = tempfile::tempdir().unwrap();
        let installations = directory.path().join("installations");
        symlink(outside.path(), &installations).unwrap();
        let cache = Cache::at(directory.path());
        let bytes = complete_archive();
        let hash = digest(&bytes);

        assert!(matches!(
            cache.install_archive(&fixture_release(), &bytes, &hash),
            Err(Error::InvalidInstallationsDirectory(actual)) if actual == installations
        ));
        assert!(outside.path().read_dir().unwrap().next().is_none());
    }

    /// Repairs a stale partial destination by publishing a complete install.
    #[test]
    fn stale_partial_destination_is_repaired() {
        let directory = tempfile::tempdir().unwrap();
        let cache = Cache::at(directory.path());
        let bytes = complete_archive();
        let hash = digest(&bytes);
        let destination = cache.installation_path_for_hash("fixture", &hash).unwrap();
        fs::create_dir_all(&destination).unwrap();
        fs::write(destination.join(Tool::Luau.file_name()), b"stale").unwrap();

        let installation = cache
            .install_archive(&fixture_release(), &bytes, &hash)
            .unwrap();
        assert_eq!(installation.path(), destination.as_path());
        assert_eq!(fs::read(installation.luau_path()).unwrap(), b"luau");
        assert_eq!(fs::read(installation.analyze_path()).unwrap(), b"analyze");
        assert_eq!(fs::read(installation.compiler_path()).unwrap(), b"compile");
        assert_eq!(fs::read(installation.ast_path().unwrap()).unwrap(), b"ast");
    }

    /// Repairs an installation when one executable no longer matches its manifest digest.
    #[test]
    fn tampered_executable_is_repaired() {
        let directory = tempfile::tempdir().unwrap();
        let cache = Cache::at(directory.path());
        let bytes = complete_archive();
        let hash = digest(&bytes);
        let installation = cache
            .install_archive(&fixture_release(), &bytes, &hash)
            .unwrap();
        fs::write(installation.luau_path(), b"tampered").unwrap();
        assert!(!is_valid_installation(installation.path(), &hash));

        let repaired = cache
            .install_archive(&fixture_release(), &bytes, &hash)
            .unwrap();
        assert_eq!(fs::read(repaired.luau_path()).unwrap(), b"luau");
        assert!(is_valid_installation(repaired.path(), &hash));
    }

    /// Rejects forged executable hashes that are not backed by the trusted archive.
    #[test]
    fn forged_manifest_cannot_authenticate_tampered_executables() {
        let directory = tempfile::tempdir().unwrap();
        let cache = Cache::at(directory.path());
        let bytes = complete_archive();
        let hash = digest(&bytes);
        let installation = cache
            .install_archive(&fixture_release(), &bytes, &hash)
            .unwrap();
        let forged_contents = [
            b"forged-luau".as_slice(),
            b"forged-analyze",
            b"forged-compile",
            b"forged-ast",
        ];
        let forged_hashes = forged_contents.map(|contents| Some(digest(contents)));
        for (tool, contents) in Tool::all().into_iter().zip(forged_contents) {
            fs::write(installation.tool_path(tool), contents).unwrap();
        }
        fs::remove_file(installation.path().join(INSTALLATION_MANIFEST_NAME)).unwrap();
        write_installation_manifest(
            installation.path(),
            &InstallationManifest::new(&hash, forged_hashes),
        )
        .unwrap();

        assert!(!is_valid_installation(installation.path(), &hash));
        let repaired = cache
            .install_archive(&fixture_release(), &bytes, &hash)
            .unwrap();
        assert_eq!(fs::read(repaired.luau_path()).unwrap(), b"luau");
        assert!(is_valid_installation(repaired.path(), &hash));
    }

    /// Repairs an installation when its hidden manifest is malformed or missing.
    #[test]
    fn tampered_or_missing_manifest_is_repaired() {
        let directory = tempfile::tempdir().unwrap();
        let cache = Cache::at(directory.path());
        let bytes = complete_archive();
        let hash = digest(&bytes);
        let installation = cache
            .install_archive(&fixture_release(), &bytes, &hash)
            .unwrap();
        let manifest = installation.path().join(INSTALLATION_MANIFEST_NAME);

        fs::write(&manifest, b"malformed manifest\n").unwrap();
        assert!(!is_valid_installation(installation.path(), &hash));
        cache
            .install_archive(&fixture_release(), &bytes, &hash)
            .unwrap();
        assert!(is_valid_installation(installation.path(), &hash));

        fs::remove_file(&manifest).unwrap();
        assert!(!is_valid_installation(installation.path(), &hash));
        cache
            .install_archive(&fixture_release(), &bytes, &hash)
            .unwrap();
        assert!(is_valid_installation(installation.path(), &hash));
    }
}
